before_install:
    - wget http://www.libsdl.org/release/SDL2-2.0.4.tar.gz -O - | tar xz
    - (cd SDL2-2.0.4 && ./configure && make && sudo make install)
    - wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.tar.gz -O - | tar xz
    - (cd SDL2_image-2.0.1 && ./configure && make && sudo make install)
language: cpp
compiler:
- clang
- gcc
script: cmake
